#Kafka properties
kafka.hub.topic=TILL_HUB_TOPIC
kafka.hub.group.id=tillHub_group_id


hub.spot.contact.url=https://api.hubapi.com/crm/v3/objects/contacts
api.key=89b7f93c-449f-452b-9887-1cbcb6d062d7
